name: Deaths
version: 1.0
main: strafeland.club.deaths.Main
api-version: 1.8
authors: [zNotHydr0]
description: Esta es la primera version para el plugin de muertes. Creado por [zNotHydr0]
website: www.strafeland.club
commands:
  deaths:
    usage: /<command> help
    aliases: [death]
  thunder:
    usage: /<command>
    aliases: [on, off]
  thunders:
    usage: /<command>
    aliases: [ on, off ]
  announce:
    usage: /<command>
    aliases: [on, off]
  menu:
    usage: /<command>
  place:
    usage: /<command>
    aliases: [ on, off ]
  break:
    usage: /<command>
    aliases: [ on, off ]
  version:
    usage: /<command>
